<Cell@Rectangle>:
    size: 10, 10

<Dirty@Cell>:
    #button for dirty one
    color: 0, 0, 1, 0

<Clean@Cell>:
    color: 0, 1, 0, 0

<Home@Cell>:
    color: 1, 0, 0 , 0

<Wall@Cell>:
    color: 1, 1, 0, 0

<Visited@Cell>:
    color: 1, 0, 1, 0
<Start@Button>
<Root>:
    Start:
        text: "Begin"
        pos:0, 0
        color: 1, 0, 1, 1
        size: 80, 80
        font_size:15
    Grid:
        pos: 60, 0
        size: 500, 500

<Grid>:
    canvas:
        Color:
            rgba: 1, 1, 0, 1
<Label1@Label>:
    pos: 0, 0
    size: 100, 100
    color: 1, 1, 0, 1
    text: "value"
#        Wall:
#            pos: 60, 60
#<Agent@Rectangle>:
#    source:'faceup.jpeg'
